apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - rules.yaml
configMapGenerator:
  - name: taskflow-dashboard
    files:
      - taskflow.json
    options:
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
