apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  description: Trusted cluster bootstrap and pinned platform controllers
  sourceRepos:
    - https://github.com/skhitrov/k8s-platform-lab.git
    - https://argoproj.github.io/argo-helm
    - https://prometheus-community.github.io/helm-charts
    - https://grafana-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://open-telemetry.github.io/opentelemetry-helm-charts
    - https://bitnami.github.io/sealed-secrets
    - https://charts.jetstack.io
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: taskflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  description: Application workloads restricted to the two lab namespaces
  sourceRepos:
    - https://github.com/skhitrov/k8s-platform-lab.git
  destinations:
    - namespace: taskflow-dev
      server: https://kubernetes.default.svc
    - namespace: taskflow-staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: batch
      kind: '*'
    - group: networking.k8s.io
      kind: '*'
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: policy
      kind: PodDisruptionBudget
    - group: monitoring.coreos.com
      kind: ServiceMonitor
    - group: argoproj.io
      kind: Rollout
    - group: argoproj.io
      kind: AnalysisTemplate
    - group: bitnami.com
      kind: SealedSecret
