{{- if .Values.api.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ include "taskflow.fullname" . }}-api
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicas }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "taskflow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  {{- if .Values.api.rollout.enabled }}
  strategy:
    canary:
      stableService: {{ include "taskflow.fullname" . }}
      canaryService: {{ include "taskflow.fullname" . }}-canary
      trafficRouting:
        nginx:
          stableIngress: {{ include "taskflow.fullname" . }}
      steps:
        {{- toYaml .Values.api.rollout.steps | nindent 8 }}
  {{- else }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "taskflow.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "taskflow.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        fsGroup: {{ .Values.podSecurity.fsGroup }}
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{- include "taskflow.selectorLabels" . | nindent 20 }}
                    app.kubernetes.io/component: api
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "taskflow.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: api
      containers:
        - name: api
          image: {{ include "taskflow.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["api"]
          securityContext:
            {{- include "taskflow.containerSecurityContext" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "taskflow.fullname" . }}
          env:
            {{- include "taskflow.databaseEnv" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health/live
              port: http
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
