{{- if .Values.api.disruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "taskflow.fullname" . }}-api
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.disruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "taskflow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
{{- if and .Values.api.disruptionBudget.enabled .Values.worker.disruptionBudget.enabled }}
---
{{- end }}
{{- if .Values.worker.disruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "taskflow.fullname" . }}-worker
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.worker.disruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "taskflow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
