{{- if .Values.sealedSecret.encryptedPassword }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.postgresql.existingSecret }}
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  encryptedData:
    {{ .Values.postgresql.passwordKey }}: {{ .Values.sealedSecret.encryptedPassword | quote }}
  template:
    metadata:
      name: {{ .Values.postgresql.existingSecret }}
      namespace: {{ .Release.Namespace }}
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/patch: "true"
    type: Opaque
{{- end }}
