apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskflow.fullname" . }}-worker
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "taskflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
